version: '3.9'

services:

  web:
    container_name: time_manager_web
    hostname: web
    restart: always
    image: nginx:latest
    ports:
      - "${IP:-0.0.0.0}:${PORT:-8080}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - front
      - back

  adminer:
    container_name: time_manager_adminer
    hostname: adminer
    image: adminer
    restart: always

  back:
    container_name: time_manager_back
    hostname: back
    build:
      context: .
      dockerfile: back.dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - db
    links:
      - db

  front:
    container_name: time_manager_front
    hostname: front
    build:
      context: .
      dockerfile: front.dockerfile
    ports:
      - "3000:3000"

  db:
    container_name: time_manager_db
    hostname: db
    restart: always
    build:
      context: .
      dockerfile: db.dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=web
      - MYSQL_DATABASE=time_manager
      - TZ=Europe/Paris
    volumes:
      - dbdrive:/var/lib/mysql
    mem_limit: 1024m
    ports:
      - "3307:3306"

volumes:
  dbdrive:
    driver: local
