version: '3.9'

services:

  back:
    container_name: time_manager_back
    hostname: back
    build:
      context: .
      dockerfile: back.dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - db

  db:
    container_name: time_manager_db
    hostname: db
    restart: always
    build:
      context: .
      dockerfile: db.dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=web
      - MYSQL_DATABASE=time_manager
      - TZ=Europe/Paris
    volumes:
      - dbdrive:/var/lib/mysql
    mem_limit: 1024m
    ports:
      - "3307:3306"

volumes:
  dbdrive:
    driver: local
