version: '3.9'

services:
  web:
    restart: always
    container_name: fcm_web
    image: nginx:latest
    ports:
      - "${IP:-0.0.0.0}:${PORT:-8080}:80"
    volumes:
      - ./back:/var/www/back
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - front
      - back

  back:
    restart: always
    container_name: fcm_back
    image: php:8-fpm
    volumes:
      - ./back:/var/www/back
      - ./zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf

  front:
    restart: always
    container_name: fcm_front
    build:
      context: .
      dockerfile: nuxt.dockerfile
